### PR TITLE
Add !byefelicia sound byte for parting users

### PR DESCRIPTION
**Pull request by ToeFrog**
## Purpose

- ...

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type

What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## How to Test

- Get the code

```
git clone git@github.com:clarkio/ttv-chat-light.git
cd ttv-chat-client
git checkout [branch-name]
npm install
```

### What to Check

Verify that the following are valid

- ...

### CODE REVIEW

**Comment by ToeFrog** [comment]
@clarkio I created a new local branch and reverted the 'sorry' change to make 'byefelicia' the only change that is here. I'll submit separate PRs for 'humpday' and 'sorry'.

**Comment by clarkio** [comment]
From our discussion on stream today, let's figure out the best approach to include this feature in a way that isn't going to over play the sound effect, won't guilt people when they have to leave and won't make the streamer feel like people are leaving in masses and being discouraged.

I do think this could be fun to include so long as we can avoid those scenarios.

**Comment by Wingysam** [comment]
Maybe it could play when someone leaves, then disable itself until a message is sent?

**Comment by clarkio** [comment]
via @PakmanJr: maybe have it so when someone sends a message with "bye" then only will it play the parting sound effect

**Comment by clarkio** [comment]
Another option via @MusicalBookworm, add this just for mods/VIPS when they leave chat since they like you and get your sense of humor.

**Comment by Wingysam** [comment]
Maybe subs too?

**Comment by Wingysam** [comment]
On stream @clarkio asked what my message means.

```js
let enabled = true
on leave () => {
  if (!enabled) return
  enabled = false
  play('byefelicia')
  once message () => { enabled = true }
}
```

**Comment by clarkio** [comment]
Ah I see now @Wingysam thanks for clarifying. So basically only enable the byefelicia sound on a departure if that user has sent a message in chat at some point during the session - otherwise don't play.

I like that idea and we should share/discuss on the next stream with the rest of chat for their input too.

**Comment by clarkio** [comment]
@all-contributors please add @ToeFrog for code and ideas

**Comment by clarkio** [comment]
@all-contributors please add @Wingysam for ideas

**Comment by clarkio** [comment]
@all-contributors please add @Wingysam for ideas

**Comment by clarkio** [comment]
Closing and will keep the issue related to this open which references this PR. If needed we can circle back to this PR when ready to implement something like this.

**Comment by clarkio** [comment]
And for realz thanks a bunch for thinking of this and taking the time to code it up!

**Pull request closed without merging**
